const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = file => JSON.parse(fs.readFileSync(path.join(root, 'seed-data', file), 'utf8'));
require('./validate-data.cjs');
const data = { phonemes:read('phonemes.json'), words:read('words.json'), graphemes:read('graphemes.json'), audio:read('audio-manifest.json'), curriculums:read('curriculum/index.json').map(id => read('curriculum/' + id + '.json')) };
fs.mkdirSync(path.join(root,'miniprogram/data'),{recursive:true});
fs.writeFileSync(path.join(root,'miniprogram/data/generated.js'), '// Generated by npm run build:data. Edit seed-data instead.\nmodule.exports = ' + JSON.stringify(data,null,2) + ';\n');
console.log('Runtime data generated.');
